# Configuração do TiDB Cloud para persistência de dados.

[connections.tidb]
dialect = "mysql+pymysql"
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
database = "grm"
username = "4V57Uk3eFQd5Hbc.root"
password = "JaCGe7LDIRDdjCKn"
